// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjq5qPGz03aoTkAymeQPwAE_OPc3tXVqE',
    appId: '1:1062198489489:android:ddc2abb284fa301319aa30',
    messagingSenderId: '1062198489489',
    projectId: 'riverpod-firestore-strea-4e9da',
    storageBucket: 'riverpod-firestore-strea-4e9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRTFi2DL6DE13-pM5oc2d7kA8ZaUBfDIU',
    appId: '1:1062198489489:ios:a696275123bf245619aa30',
    messagingSenderId: '1062198489489',
    projectId: 'riverpod-firestore-strea-4e9da',
    storageBucket: 'riverpod-firestore-strea-4e9da.appspot.com',
    iosClientId: '1062198489489-supfjo9e1crd37joicvc9g39rf990at4.apps.googleusercontent.com',
    iosBundleId: 'shop.mtcoding.riverpodFirestoreStream',
  );
}
